version: '3.4'

services:
  database:
    platform: linux/x86_64
    image: mysql:8.0
    restart: always
    volumes:
      - ./.docker/mysql.cnf:/etc/mysql/conf.d/custom.cf:ro
      - cosmic-db-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=cosmic
      - MYSQL_USER=cosmic
      - MYSQL_PASSWORD=cosmic
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - cosmic

  app:
    build:
      context: .docker/
    depends_on:
      - database
    volumes:
      - ./:/var/www/html:rw,cached
      - ~/.composer:/var/www/html/.composer
      - sf-cache:/var/www/html/var/cache:rw
    networks:
      - cosmic

  nginx:
    image: nginx:1.14-alpine
    links:
      - app:app
    volumes:
      - ./public:/var/www/html/public:ro
      - ./.docker/nginx.default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "81:80"
    networks:
      - cosmic

  phpmyadmin:
    platform: linux/x86_64
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      MYSQL_USER: cosmic
      MYSQL_PASSWORD: cosmic
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "88:80"
    depends_on:
      - database
    networks:
      - cosmic

volumes:
  cosmic-db-data: {}
  sf-cache: {}

networks:
  cosmic:
    driver: 'bridge'
